"""`specy-road refresh-stubs`: the safe path between `init` and `init --force`.

Without this command, a repo that upgraded specy-road had no way to pick up
stubs added since it was scaffolded except `init --force`, which is what led a
consumer to lose a hand-authored `CLAUDE.md`. So the contract is narrow on
purpose: exactly the paths `.specyrd/manifest.json` records, plus the managed
blocks, and nothing else.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from specy_road import __version__
from specy_road.bundled_scripts.refresh_stubs import (
    refresh_stubs,
    stubs_are_stale,
    warn_if_stubs_stale,
)

OLD_VERSION = "0.1.4"
OLD_DEV_STUBS = (
    "specyrd-validate",
    "specyrd-brief",
    "specyrd-claim",
    "specyrd-finish",
    "specyrd-do-next-task",
)
CONSUMER_CLAUDE_MD = "# My App\n\n## Rules\n\n- Never push to main.\n"


def _old_repo(tmp_path: Path, *, extra_recorded: list[str] | None = None) -> Path:
    """A repo scaffolded by an older specyrd: stale stubs, no context tools."""
    commands = tmp_path / ".claude" / "commands"
    commands.mkdir(parents=True)
    recorded = []
    for name in OLD_DEV_STUBS:
        (commands / f"{name}.md").write_text("stale stub\n", encoding="utf-8")
        recorded.append(f".claude/commands/{name}.md")
    recorded.append(".specyrd/README.md")
    recorded.extend(extra_recorded or [])
    (tmp_path / "CLAUDE.md").write_text(CONSUMER_CLAUDE_MD, encoding="utf-8")
    manifest = tmp_path / ".specyrd" / "manifest.json"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(
        json.dumps(
            {
                "specyrd_version": OLD_VERSION,
                "agents": {"claude-code": recorded},
                "role": "dev",
                "project_root": ".",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return tmp_path


def _manifest(root: Path) -> dict:
    return json.loads(
        (root / ".specyrd" / "manifest.json").read_text(encoding="utf-8")
    )


def test_an_uninitialized_repo_is_told_to_run_init(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="specyrd init"):
        refresh_stubs(tmp_path)


def test_stubs_shipped_since_the_repo_was_scaffolded_are_added(
    tmp_path: Path,
) -> None:
    """The 0.2.1 context tools were reachable only by force-overwriting."""
    root = _old_repo(tmp_path)

    written, _ = refresh_stubs(root)

    for name in ("specyrd-search", "specyrd-digest", "specyrd-history"):
        assert f".claude/commands/{name}.md" in written
        assert (root / ".claude" / "commands" / f"{name}.md").is_file()


def test_stale_stubs_are_rewritten_and_the_version_is_bumped(
    tmp_path: Path,
) -> None:
    root = _old_repo(tmp_path)

    refresh_stubs(root)

    stub = root / ".claude" / "commands" / "specyrd-validate.md"
    assert "stale stub" not in stub.read_text(encoding="utf-8")
    assert f"Generated by specyrd {__version__}." in stub.read_text(encoding="utf-8")
    assert _manifest(root)["specyrd_version"] == __version__


def test_a_second_run_changes_nothing(tmp_path: Path) -> None:
    root = _old_repo(tmp_path)
    refresh_stubs(root)

    written, orphans = refresh_stubs(root)

    assert written == []
    assert orphans == []


def test_the_consumer_half_of_claude_md_is_untouched(tmp_path: Path) -> None:
    root = _old_repo(tmp_path)

    refresh_stubs(root)
    text = (root / "CLAUDE.md").read_text(encoding="utf-8")

    assert text.startswith(CONSUMER_CLAUDE_MD)
    assert "specy-road managed block" in text


def test_orphaned_stubs_are_reported_not_deleted(tmp_path: Path) -> None:
    """A narrower --role drops paths from the manifest; the files stay ours to keep."""
    orphan_rel = ".claude/commands/specyrd-add-node.md"
    root = _old_repo(tmp_path, extra_recorded=[orphan_rel])
    (root / orphan_rel).write_text("pm-only stub\n", encoding="utf-8")

    _, orphans = refresh_stubs(root)

    assert orphan_rel in orphans
    assert (root / orphan_rel).read_text(encoding="utf-8") == "pm-only stub\n"
    assert orphan_rel not in _manifest(root)["agents"]["claude-code"]


def test_a_dry_run_reports_everything_and_writes_nothing(tmp_path: Path) -> None:
    root = _old_repo(tmp_path)

    written, _ = refresh_stubs(root, dry_run=True)

    assert ".claude/commands/specyrd-search.md" in written
    assert any(w.startswith("CLAUDE.md (") for w in written)
    assert not (root / ".claude" / "commands" / "specyrd-search.md").exists()
    assert (root / "CLAUDE.md").read_text(encoding="utf-8") == CONSUMER_CLAUDE_MD
    assert _manifest(root)["specyrd_version"] == OLD_VERSION


def test_validate_warns_once_while_the_stubs_lag(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    root = _old_repo(tmp_path)
    assert stubs_are_stale(root) == OLD_VERSION

    warn_if_stubs_stale(root)
    assert "specy-road refresh-stubs" in capsys.readouterr().err

    refresh_stubs(root)
    assert stubs_are_stale(root) is None
    warn_if_stubs_stale(root)
    assert capsys.readouterr().err == ""


def test_a_repo_with_no_specyrd_stubs_never_warns(tmp_path: Path) -> None:
    assert stubs_are_stale(tmp_path) is None
