"""The ``specy-road`` top-level help text.

Split out of ``cli.py`` so the dispatcher stays under the file-line cap: this is
pure data that grows with every command, and it was crowding out the code.
"""

from __future__ import annotations

USAGE_TEXT = (
    "Usage: specy-road <command> [args...]\n"
    "\n"
    "  --version, -V        — print the installed specy-road version\n"
    "\n"
    "Authoring / validation:\n"
    "  validate             — validate merged roadmap graph and registry\n"
    "  brief <NODE_ID>      — generate focused brief for a node\n"
    "    (inlines shared/ contracts cited in the chain's `## References`;\n"
    "     --all-contracts inlines every shared/**/*.md instead)\n"
    "  export               — regenerate roadmap.md index from merged graph\n"
    "  file-limits          — check line-count constraints\n"
    "\n"
    "PM workflow:\n"
    "  brainstorm           — generate roadmap ideas with an agent, then promote\n"
    "    the ones you keep. `start` diverges (quantity, Socratic questioning,\n"
    "    research); `recommend` converges (cluster and rank); accept/reject/revise\n"
    "    is the PM's triage; `promote` writes accepted ideas into the graph.\n"
    "    (see: specy-road brainstorm -h)\n"
    "  sync                 — fetch/merge integration branch, validate, export, digest\n"
    "    (optional: --base BRANCH --remote NAME)\n"
    "  list-nodes           — list nodes and chunk paths (pass-through to roadmap CRUD)\n"
    "    (optional: --status STATUS, repeatable; filters on the ROLLUP column)\n"
    "  show-node <NODE_ID>  — stdout is pure JSON (pipe it); the source chunk\n"
    "    path is printed to stderr\n"
    "  add-node ...         — see: python specy_road/bundled_scripts/roadmap_crud.py add-node -h\n"
    "    (--chunk is now optional; specy-road auto-routes to a valid chunk)\n"
    "  edit-node ...\n"
    "  move-node <NODE_ID> --to-parent <PARENT_NODE_ID|null> — re-parent a subtree and\n"
    "    renumber display ids; renames planning sheets and updates registry claims\n"
    "    (optional: --index N --repo-root DIR). edit-node --set parent_id= does NOT renumber.\n"
    "  set-gate-status <NODE_ID> --status … — gate nodes only (Not Started|In Progress|Complete|Blocked)\n"
    "  list-gates           — gate nodes still holding work back, and what each blocks\n"
    "    (optional: --under NODE_ID --json --repo-root DIR)\n"
    "  archive-node ...         — legacy hard-remove; see `archive` below to archive completed work\n"
    "\n"
    "Archiving (long-running roadmaps):\n"
    "  archive <NODE_ID>    — move a Complete subtree out of the live graph into roadmap/archive/\n"
    "    (optional: --deep --dry-run --force | --auto [--older-than-days N])\n"
    "  deepen-archive <ARCHIVE_ID> — fold a shallow archive into one capsule file + reference\n"
    "  list-archives        — list archive records (optional: --json)\n"
    "  show-archive <ARCHIVE_ID> — one record in detail, including git provenance\n"
    "  restore-archive <ARCHIVE_ID> — bring an archived subtree back (optional: --dry-run)\n"
    "\n"
    "History (derived from git, cached under .specyrd/cache/):\n"
    "  history [NODE_ID]    — how a node got here: status changes, dependency edges,\n"
    "    renumbering, archived work. A node's timeline reads oldest first; omit\n"
    "    NODE_ID for a roadmap-wide feed, which reads newest first.\n"
    "    (optional: --since DATE --archived --limit N --reverse --json --rebuild\n"
    "     --repo-root DIR)\n"
    "\n"
    "Agent context (keeps IDE indexing small):\n"
    "  search <QUERY>       — ranked search over planning sheets, shared contracts,\n"
    "    roadmap nodes, implementation summaries and archived work\n"
    "    (optional: --scope live|archived|all --kind K --node ID --limit N --json\n"
    "     --stats --rebuild --repo-root DIR)\n"
    "  digest               — write roadmap-context.md: the current state in one file,\n"
    "    for an agent to read instead of crawling planning/ and work/. Generated\n"
    "    AND committed, like roadmap.md; --check is its drift gate.\n"
    "    (optional: -o FILE | -o - for stdout | --check --repo-root DIR)\n"
    "\n"
    "Roadmap editing:\n"
    "  list-dependencies <NODE_ID>\n"
    "  set-dependencies <NODE_ID> (--clear | --deps \"KEY …\")\n"
    "  add-dependency <NODE_ID> <DEP_NODE_KEY>\n"
    "  remove-dependency <NODE_ID> <DEP_NODE_KEY>\n"
    "  rebalance-chunks     — re-pack roadmap chunks deterministically when a chunk\n"
    "    exceeds the line cap (optional: --repo-root DIR --dry-run)\n"
    "  refresh-schemas      — update schemas/ from this specy-road version; touches\n"
    "    nothing else (optional: --repo-root DIR --dry-run)\n"
    "  refresh-stubs        — update the IDE stubs .specyrd/manifest.json records,\n"
    "    add ones shipped since, re-apply the managed blocks; touches nothing else\n"
    "    (optional: --repo-root DIR --dry-run)\n"
    "  review-node <NODE_ID> — advisory LLM review (requires pip install specy-road[review])\n"
    "  scaffold-planning <NODE_ID> — create planning/<id>_<slug>_<node_key>.md; set planning_dir\n"
    "    (optional: --planning-dir PATH --force; see specy_road/bundled_scripts/scaffold_planning.py -h)\n"
    "  scaffold-constitution — create constitution/purpose.md and constitution/principles.md from templates\n"
    "    (optional: --repo-root DIR --force)\n"
    "  init project [PATH] — scaffold roadmap/constitution/shared/… into the repo root\n"
    "    (optional: --dry-run --force)\n"
    "  init gui — optional PM UI: --install-gui | --reinstall-gui | --build-gui [--skip-npm-build]\n"
    "  update — fast-forward a git clone of specy-road from github.com/shanevigil/specy-road "
    "(optional: --path DIR --remote NAME --branch BRANCH --dry-run --install-gui-stack)\n"
    "  gui — FastAPI + Gantt PM UI (after: init --install-gui or pip install 'specy-road[gui-next]')\n"
    "\n"
    "Dev task loop:\n"
    "  do-next-available-task  — sync base, pick actionable leaf, brief, register on base, push base, branch, prompt\n"
    "    (optional: --base BRANCH --remote NAME | --interactive | "
    "--no-ci-skip-in-message | --on-complete MODE | --milestone-subtree | "
    "--under NODE_ID)\n"
    "    Selection: Blocked leaves are offered FIRST, then MR-rejected, then the\n"
    "    rest in outline order. execution_milestone (Human-led/…) is advisory and\n"
    "    does not gate pickup; use a type: gate dependency to hold work back.\n"
    "    --under takes a parent (its whole subtree) or one leaf id.\n"
    "    An existing feature/rm-* branch is checked out, not treated as a failure.\n"
    "  abort-task-pickup       — undo pickup: deregister on base, push base, delete local feature/rm-*, clean work/\n"
    "    (optional: --base BRANCH --remote NAME | --force)\n"
    "  why-blocked <NODE_ID>   — why one node is not pickable: the transitive chain of\n"
    "    unmet dependencies, an open gate, an existing claim, or a missing codename\n"
    "    (optional: --json --repo-root DIR; exits 1 when it really is blocked)\n"
    "  mark-implementation-reviewed — human gate: record review after implementation-summary\n"
    "    (optional: --yes | --allow-missing-summary)\n"
    "  finish-this-task        — complete task, validate, export, digest, commit;\n"
    "    land pr|merge|auto\n"
    "    (optional: --push [--remote NAME] | --no-cleanup-work | --no-milestone-rollup)\n"
    "    Finishing the last open leaf under a parent also closes that parent in the\n"
    "    same bookkeeping commit — except milestone-session nodes, which\n"
    "    reconcile-milestone-status closes once the rollup branch is proven merged.\n"
    "  grind-session           — orchestrate pickup->implement->finish over many leaves\n"
    "    (--plan for read-only ready/blocked/waves; --until NODE | --under PARENT | "
    "--max-leaves N | --implement-mode {manual,hook} --implement-cmd CMD | "
    "--pre-finish-cmd CMD | --on-complete {pr,merge,auto} | --json | "
    "--resume-in-flight | --delete-merged-branches)\n"
    "    Stopping with exit 6 means this worktree already holds a claim: finish it,\n"
    "    abort-task-pickup, or re-run with --resume-in-flight. Exit 3 is a real\n"
    "    dependency/gate block needing human action elsewhere.\n"
    "  start-milestone-session <PARENT_NODE_ID> — sync base, ensure rollup branch, write work/.milestone-session.yaml\n"
    "    (optional: --base BRANCH --remote NAME --repo-root DIR)\n"
    "  reconcile-milestone-status — dry-run milestone delivery vs git; --apply to close/sync (see -h)\n"
    "  open-milestone-pr       — print gh/glab one-line PR from rollup branch to integration\n"
)
